// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: cortex.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountType int32

const (
	AccountType_HUMAN     AccountType = 0 // 일반 유저 (원형 프사)
	AccountType_AUTOMATON AccountType = 1 // 봇 (육각형 프사, [BOT] 태그)
	AccountType_CONSTRUCT AccountType = 2 // 시스템 관리 봇
	AccountType_PROXY     AccountType = 3 // 외부 브릿지 (디스코드 등)
)

// Enum value maps for AccountType.
var (
	AccountType_name = map[int32]string{
		0: "HUMAN",
		1: "AUTOMATON",
		2: "CONSTRUCT",
		3: "PROXY",
	}
	AccountType_value = map[string]int32{
		"HUMAN":     0,
		"AUTOMATON": 1,
		"CONSTRUCT": 2,
		"PROXY":     3,
	}
)

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}

func (x AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_cortex_proto_enumTypes[0].Descriptor()
}

func (AccountType) Type() protoreflect.EnumType {
	return &file_cortex_proto_enumTypes[0]
}

func (x AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountType.Descriptor instead.
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{0}
}

type ChatEvent_RelationType int32

const (
	ChatEvent_NEW    ChatEvent_RelationType = 0 // 새 메시지
	ChatEvent_REPLY  ChatEvent_RelationType = 1 // 답장
	ChatEvent_EDIT   ChatEvent_RelationType = 2 // 수정 (덮어쓰기)
	ChatEvent_DELETE ChatEvent_RelationType = 3 // 삭제 (Tombstone)
)

// Enum value maps for ChatEvent_RelationType.
var (
	ChatEvent_RelationType_name = map[int32]string{
		0: "NEW",
		1: "REPLY",
		2: "EDIT",
		3: "DELETE",
	}
	ChatEvent_RelationType_value = map[string]int32{
		"NEW":    0,
		"REPLY":  1,
		"EDIT":   2,
		"DELETE": 3,
	}
)

func (x ChatEvent_RelationType) Enum() *ChatEvent_RelationType {
	p := new(ChatEvent_RelationType)
	*p = x
	return p
}

func (x ChatEvent_RelationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatEvent_RelationType) Descriptor() protoreflect.EnumDescriptor {
	return file_cortex_proto_enumTypes[1].Descriptor()
}

func (ChatEvent_RelationType) Type() protoreflect.EnumType {
	return &file_cortex_proto_enumTypes[1]
}

func (x ChatEvent_RelationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatEvent_RelationType.Descriptor instead.
func (ChatEvent_RelationType) EnumDescriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{8, 0}
}

type VoiceSignal_SignalType int32

const (
	VoiceSignal_JOIN_REQUEST VoiceSignal_SignalType = 0
	VoiceSignal_TOKEN_ISSUED VoiceSignal_SignalType = 1
	VoiceSignal_USER_LEFT    VoiceSignal_SignalType = 2
)

// Enum value maps for VoiceSignal_SignalType.
var (
	VoiceSignal_SignalType_name = map[int32]string{
		0: "JOIN_REQUEST",
		1: "TOKEN_ISSUED",
		2: "USER_LEFT",
	}
	VoiceSignal_SignalType_value = map[string]int32{
		"JOIN_REQUEST": 0,
		"TOKEN_ISSUED": 1,
		"USER_LEFT":    2,
	}
)

func (x VoiceSignal_SignalType) Enum() *VoiceSignal_SignalType {
	p := new(VoiceSignal_SignalType)
	*p = x
	return p
}

func (x VoiceSignal_SignalType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VoiceSignal_SignalType) Descriptor() protoreflect.EnumDescriptor {
	return file_cortex_proto_enumTypes[2].Descriptor()
}

func (VoiceSignal_SignalType) Type() protoreflect.EnumType {
	return &file_cortex_proto_enumTypes[2]
}

func (x VoiceSignal_SignalType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VoiceSignal_SignalType.Descriptor instead.
func (VoiceSignal_SignalType) EnumDescriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{11, 0}
}

type SystemSignal_SignalType int32

const (
	SystemSignal_MAINTENANCE         SystemSignal_SignalType = 0 // 이주 잠금 (Lock)
	SystemSignal_SHUTDOWN_PERMANENT  SystemSignal_SignalType = 1 // 이주 해제 (Unlock)
	SystemSignal_MIGRATION_IMMEDIATE SystemSignal_SignalType = 2 // 즉시 리다이렉트
)

// Enum value maps for SystemSignal_SignalType.
var (
	SystemSignal_SignalType_name = map[int32]string{
		0: "MAINTENANCE",
		1: "SHUTDOWN_PERMANENT",
		2: "MIGRATION_IMMEDIATE",
	}
	SystemSignal_SignalType_value = map[string]int32{
		"MAINTENANCE":         0,
		"SHUTDOWN_PERMANENT":  1,
		"MIGRATION_IMMEDIATE": 2,
	}
)

func (x SystemSignal_SignalType) Enum() *SystemSignal_SignalType {
	p := new(SystemSignal_SignalType)
	*p = x
	return p
}

func (x SystemSignal_SignalType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SystemSignal_SignalType) Descriptor() protoreflect.EnumDescriptor {
	return file_cortex_proto_enumTypes[3].Descriptor()
}

func (SystemSignal_SignalType) Type() protoreflect.EnumType {
	return &file_cortex_proto_enumTypes[3]
}

func (x SystemSignal_SignalType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SystemSignal_SignalType.Descriptor instead.
func (SystemSignal_SignalType) EnumDescriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{12, 0}
}

type UserProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Did           string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`           // did:cortex:pubkey...
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"` // 표시 이름 (Nero)
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`     // 홈 서버 도메인 (ludus.gg)
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Bio           string                 `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	Type          AccountType            `protobuf:"varint,6,opt,name=type,proto3,enum=cortex.v1.AccountType" json:"type,omitempty"`
	IsVerified    bool                   `protobuf:"varint,7,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"` // 공식 인증 마크
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_cortex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{0}
}

func (x *UserProfile) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *UserProfile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserProfile) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *UserProfile) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UserProfile) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UserProfile) GetType() AccountType {
	if x != nil {
		return x.Type
	}
	return AccountType_HUMAN
}

func (x *UserProfile) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

// [E2EE] 키 교환용 번들 (서버에 업로드/다운로드)
type KeyBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityKey   string                 `protobuf:"bytes,1,opt,name=identity_key,json=identityKey,proto3" json:"identity_key,omitempty"`      // IK (불변)
	SignedPreKey  string                 `protobuf:"bytes,2,opt,name=signed_pre_key,json=signedPreKey,proto3" json:"signed_pre_key,omitempty"` // SPK (중기)
	SpkSignature  []byte                 `protobuf:"bytes,3,opt,name=spk_signature,json=spkSignature,proto3" json:"spk_signature,omitempty"`   // SPK 서명
	OneTimeKey    string                 `protobuf:"bytes,4,opt,name=one_time_key,json=oneTimeKey,proto3" json:"one_time_key,omitempty"`       // OPK (일회용 - 가져가면 삭제됨)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyBundle) Reset() {
	*x = KeyBundle{}
	mi := &file_cortex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyBundle) ProtoMessage() {}

func (x *KeyBundle) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyBundle.ProtoReflect.Descriptor instead.
func (*KeyBundle) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{1}
}

func (x *KeyBundle) GetIdentityKey() string {
	if x != nil {
		return x.IdentityKey
	}
	return ""
}

func (x *KeyBundle) GetSignedPreKey() string {
	if x != nil {
		return x.SignedPreKey
	}
	return ""
}

func (x *KeyBundle) GetSpkSignature() []byte {
	if x != nil {
		return x.SpkSignature
	}
	return nil
}

func (x *KeyBundle) GetOneTimeKey() string {
	if x != nil {
		return x.OneTimeKey
	}
	return ""
}

// 1. 회원가입 요청
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *UserProfile           `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"` // Sign(profile_bytes, MyPrivateKey)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_cortex_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *RegisterRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AccessToken   string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"` // 가입 즉시 로그인 처리용
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_cortex_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

// 2. 로그인 챌린지 (서버가 문제를 냄)
type AuthChallenge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Did           string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	Nonce         string                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"` // 랜덤 문자열 (32 bytes hex)
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthChallenge) Reset() {
	*x = AuthChallenge{}
	mi := &file_cortex_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthChallenge) ProtoMessage() {}

func (x *AuthChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthChallenge.ProtoReflect.Descriptor instead.
func (*AuthChallenge) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{4}
}

func (x *AuthChallenge) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *AuthChallenge) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *AuthChallenge) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// 3. 로그인 응답 (클라가 문제를 품)
type AuthLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Did           string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	Nonce         string                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"` // Sign(nonce, MyPrivateKey)
	DeviceName    string                 `protobuf:"bytes,4,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthLogin) Reset() {
	*x = AuthLogin{}
	mi := &file_cortex_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthLogin) ProtoMessage() {}

func (x *AuthLogin) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthLogin.ProtoReflect.Descriptor instead.
func (*AuthLogin) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{5}
}

func (x *AuthLogin) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *AuthLogin) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *AuthLogin) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AuthLogin) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

// 4. 토큰 발급
type TokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_cortex_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{6}
}

func (x *TokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *TokenResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

// 모든 이벤트는 이 Impulse에 담겨 전송됩니다.
type Impulse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// --- 메타데이터 ---
	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                // SHA256 Hash
	Timestamp int64  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix Nano
	SenderDid string `protobuf:"bytes,3,opt,name=sender_did,json=senderDid,proto3" json:"sender_did,omitempty"`
	GuildId   string `protobuf:"bytes,4,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`       // (Optional)
	ChannelId string `protobuf:"bytes,5,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"` // (Optional)
	// --- 보안 (Client Signing) ---
	// 서버가 내용을 위조하면 이 서명이 깨집니다.
	Signature []byte `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	// --- 내용 (Payload) ---
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*Impulse_Chat
	//	*Impulse_Voice
	//	*Impulse_System
	//	*Impulse_Migration
	//	*Impulse_Report
	Payload       isImpulse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Impulse) Reset() {
	*x = Impulse{}
	mi := &file_cortex_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Impulse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Impulse) ProtoMessage() {}

func (x *Impulse) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Impulse.ProtoReflect.Descriptor instead.
func (*Impulse) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{7}
}

func (x *Impulse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Impulse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Impulse) GetSenderDid() string {
	if x != nil {
		return x.SenderDid
	}
	return ""
}

func (x *Impulse) GetGuildId() string {
	if x != nil {
		return x.GuildId
	}
	return ""
}

func (x *Impulse) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *Impulse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Impulse) GetPayload() isImpulse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Impulse) GetChat() *ChatEvent {
	if x != nil {
		if x, ok := x.Payload.(*Impulse_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *Impulse) GetVoice() *VoiceSignal {
	if x != nil {
		if x, ok := x.Payload.(*Impulse_Voice); ok {
			return x.Voice
		}
	}
	return nil
}

func (x *Impulse) GetSystem() *SystemSignal {
	if x != nil {
		if x, ok := x.Payload.(*Impulse_System); ok {
			return x.System
		}
	}
	return nil
}

func (x *Impulse) GetMigration() *MigrationCertificate {
	if x != nil {
		if x, ok := x.Payload.(*Impulse_Migration); ok {
			return x.Migration
		}
	}
	return nil
}

func (x *Impulse) GetReport() *AbuseReport {
	if x != nil {
		if x, ok := x.Payload.(*Impulse_Report); ok {
			return x.Report
		}
	}
	return nil
}

type isImpulse_Payload interface {
	isImpulse_Payload()
}

type Impulse_Chat struct {
	Chat *ChatEvent `protobuf:"bytes,10,opt,name=chat,proto3,oneof"`
}

type Impulse_Voice struct {
	Voice *VoiceSignal `protobuf:"bytes,11,opt,name=voice,proto3,oneof"`
}

type Impulse_System struct {
	System *SystemSignal `protobuf:"bytes,12,opt,name=system,proto3,oneof"`
}

type Impulse_Migration struct {
	Migration *MigrationCertificate `protobuf:"bytes,13,opt,name=migration,proto3,oneof"`
}

type Impulse_Report struct {
	Report *AbuseReport `protobuf:"bytes,14,opt,name=report,proto3,oneof"`
}

func (*Impulse_Chat) isImpulse_Payload() {}

func (*Impulse_Voice) isImpulse_Payload() {}

func (*Impulse_System) isImpulse_Payload() {}

func (*Impulse_Migration) isImpulse_Payload() {}

func (*Impulse_Report) isImpulse_Payload() {}

type ChatEvent struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	RelType     ChatEvent_RelationType `protobuf:"varint,1,opt,name=rel_type,json=relType,proto3,enum=cortex.v1.ChatEvent_RelationType" json:"rel_type,omitempty"`
	RefId       string                 `protobuf:"bytes,2,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`                    // 대상 메시지 ID (수정/답장 시)
	IsEncrypted bool                   `protobuf:"varint,3,opt,name=is_encrypted,json=isEncrypted,proto3" json:"is_encrypted,omitempty"` // E2EE 여부
	// Types that are valid to be assigned to Content:
	//
	//	*ChatEvent_PlainText
	//	*ChatEvent_Encrypted
	Content       isChatEvent_Content `protobuf_oneof:"content"`
	Attachments   []*Attachment       `protobuf:"bytes,6,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatEvent) Reset() {
	*x = ChatEvent{}
	mi := &file_cortex_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatEvent) ProtoMessage() {}

func (x *ChatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatEvent.ProtoReflect.Descriptor instead.
func (*ChatEvent) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{8}
}

func (x *ChatEvent) GetRelType() ChatEvent_RelationType {
	if x != nil {
		return x.RelType
	}
	return ChatEvent_NEW
}

func (x *ChatEvent) GetRefId() string {
	if x != nil {
		return x.RefId
	}
	return ""
}

func (x *ChatEvent) GetIsEncrypted() bool {
	if x != nil {
		return x.IsEncrypted
	}
	return false
}

func (x *ChatEvent) GetContent() isChatEvent_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ChatEvent) GetPlainText() string {
	if x != nil {
		if x, ok := x.Content.(*ChatEvent_PlainText); ok {
			return x.PlainText
		}
	}
	return ""
}

func (x *ChatEvent) GetEncrypted() *EncryptedData {
	if x != nil {
		if x, ok := x.Content.(*ChatEvent_Encrypted); ok {
			return x.Encrypted
		}
	}
	return nil
}

func (x *ChatEvent) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

type isChatEvent_Content interface {
	isChatEvent_Content()
}

type ChatEvent_PlainText struct {
	PlainText string `protobuf:"bytes,4,opt,name=plain_text,json=plainText,proto3,oneof"` // 평문 (공개 채널)
}

type ChatEvent_Encrypted struct {
	Encrypted *EncryptedData `protobuf:"bytes,5,opt,name=encrypted,proto3,oneof"` // 암호문 (비공개/DM)
}

func (*ChatEvent_PlainText) isChatEvent_Content() {}

func (*ChatEvent_Encrypted) isChatEvent_Content() {}

type EncryptedData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ciphertext    []byte                 `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Algorithm     string                 `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`                          // "m.megolm.v1.aes-sha2"
	SenderKeyId   string                 `protobuf:"bytes,3,opt,name=sender_key_id,json=senderKeyId,proto3" json:"sender_key_id,omitempty"` // 복호화 세션 키 ID
	DeviceId      string                 `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedData) Reset() {
	*x = EncryptedData{}
	mi := &file_cortex_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedData) ProtoMessage() {}

func (x *EncryptedData) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedData.ProtoReflect.Descriptor instead.
func (*EncryptedData) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{9}
}

func (x *EncryptedData) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *EncryptedData) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *EncryptedData) GetSenderKeyId() string {
	if x != nil {
		return x.SenderKeyId
	}
	return ""
}

func (x *EncryptedData) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type Attachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Hash          string                 `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"` // 불법 파일 필터링용 해시
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_cortex_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{10}
}

func (x *Attachment) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Attachment) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Attachment) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Attachment) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Attachment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// LiveKit SFU 연결용
type VoiceSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          VoiceSignal_SignalType `protobuf:"varint,1,opt,name=type,proto3,enum=cortex.v1.VoiceSignal_SignalType" json:"type,omitempty"`
	SfuUrl        string                 `protobuf:"bytes,2,opt,name=sfu_url,json=sfuUrl,proto3" json:"sfu_url,omitempty"` // UDP Direct 주소
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`                 // JWT Access Token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoiceSignal) Reset() {
	*x = VoiceSignal{}
	mi := &file_cortex_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceSignal) ProtoMessage() {}

func (x *VoiceSignal) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceSignal.ProtoReflect.Descriptor instead.
func (*VoiceSignal) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{11}
}

func (x *VoiceSignal) GetType() VoiceSignal_SignalType {
	if x != nil {
		return x.Type
	}
	return VoiceSignal_JOIN_REQUEST
}

func (x *VoiceSignal) GetSfuUrl() string {
	if x != nil {
		return x.SfuUrl
	}
	return ""
}

func (x *VoiceSignal) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 서버 생존 신호 (단말마)
type SystemSignal struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	Type            SystemSignal_SignalType `protobuf:"varint,1,opt,name=type,proto3,enum=cortex.v1.SystemSignal_SignalType" json:"type,omitempty"`
	Message         string                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RedirectUrl     string                  `protobuf:"bytes,3,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	ServerSignature []byte                  `protobuf:"bytes,4,opt,name=server_signature,json=serverSignature,proto3" json:"server_signature,omitempty"` // 서버 키 서명
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SystemSignal) Reset() {
	*x = SystemSignal{}
	mi := &file_cortex_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemSignal) ProtoMessage() {}

func (x *SystemSignal) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemSignal.ProtoReflect.Descriptor instead.
func (*SystemSignal) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{12}
}

func (x *SystemSignal) GetType() SystemSignal_SignalType {
	if x != nil {
		return x.Type
	}
	return SystemSignal_MAINTENANCE
}

func (x *SystemSignal) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SystemSignal) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

func (x *SystemSignal) GetServerSignature() []byte {
	if x != nil {
		return x.ServerSignature
	}
	return nil
}

// 도메인 변경 증명서
type MigrationCertificate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldDomain     string                 `protobuf:"bytes,1,opt,name=old_domain,json=oldDomain,proto3" json:"old_domain,omitempty"`
	NewDomain     string                 `protobuf:"bytes,2,opt,name=new_domain,json=newDomain,proto3" json:"new_domain,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"` // 구 서버 키 서명
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationCertificate) Reset() {
	*x = MigrationCertificate{}
	mi := &file_cortex_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationCertificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationCertificate) ProtoMessage() {}

func (x *MigrationCertificate) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationCertificate.ProtoReflect.Descriptor instead.
func (*MigrationCertificate) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{13}
}

func (x *MigrationCertificate) GetOldDomain() string {
	if x != nil {
		return x.OldDomain
	}
	return ""
}

func (x *MigrationCertificate) GetNewDomain() string {
	if x != nil {
		return x.NewDomain
	}
	return ""
}

func (x *MigrationCertificate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MigrationCertificate) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// 자정 작용 (신고)
type AbuseReport struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ReporterDid            string                 `protobuf:"bytes,1,opt,name=reporter_did,json=reporterDid,proto3" json:"reporter_did,omitempty"`
	TargetMessageId        string                 `protobuf:"bytes,2,opt,name=target_message_id,json=targetMessageId,proto3" json:"target_message_id,omitempty"`
	Reason                 string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	EphemeralDecryptionKey []byte                 `protobuf:"bytes,4,opt,name=ephemeral_decryption_key,json=ephemeralDecryptionKey,proto3" json:"ephemeral_decryption_key,omitempty"` // 신고용 임시 키
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AbuseReport) Reset() {
	*x = AbuseReport{}
	mi := &file_cortex_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbuseReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbuseReport) ProtoMessage() {}

func (x *AbuseReport) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbuseReport.ProtoReflect.Descriptor instead.
func (*AbuseReport) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{14}
}

func (x *AbuseReport) GetReporterDid() string {
	if x != nil {
		return x.ReporterDid
	}
	return ""
}

func (x *AbuseReport) GetTargetMessageId() string {
	if x != nil {
		return x.TargetMessageId
	}
	return ""
}

func (x *AbuseReport) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AbuseReport) GetEphemeralDecryptionKey() []byte {
	if x != nil {
		return x.EphemeralDecryptionKey
	}
	return nil
}

type GatewayPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            int32                  `protobuf:"varint,1,opt,name=op,proto3" json:"op,omitempty"` // OpCode (0: Dispatch, 1: Heartbeat, ...)
	D             []byte                 `protobuf:"bytes,2,opt,name=d,proto3" json:"d,omitempty"`    // Data (Impulse 등 실제 데이터)
	T             string                 `protobuf:"bytes,3,opt,name=t,proto3" json:"t,omitempty"`    // Type ("MESSAGE_CREATE" 등)
	S             int64                  `protobuf:"varint,4,opt,name=s,proto3" json:"s,omitempty"`   // Sequence Number
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayPayload) Reset() {
	*x = GatewayPayload{}
	mi := &file_cortex_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayPayload) ProtoMessage() {}

func (x *GatewayPayload) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayPayload.ProtoReflect.Descriptor instead.
func (*GatewayPayload) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{15}
}

func (x *GatewayPayload) GetOp() int32 {
	if x != nil {
		return x.Op
	}
	return 0
}

func (x *GatewayPayload) GetD() []byte {
	if x != nil {
		return x.D
	}
	return nil
}

func (x *GatewayPayload) GetT() string {
	if x != nil {
		return x.T
	}
	return ""
}

func (x *GatewayPayload) GetS() int64 {
	if x != nil {
		return x.S
	}
	return 0
}

var File_cortex_proto protoreflect.FileDescriptor

const file_cortex_proto_rawDesc = "" +
	"\n" +
	"\fcortex.proto\x12\tcortex.v1\"\xd1\x01\n" +
	"\vUserProfile\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12\x10\n" +
	"\x03bio\x18\x05 \x01(\tR\x03bio\x12*\n" +
	"\x04type\x18\x06 \x01(\x0e2\x16.cortex.v1.AccountTypeR\x04type\x12\x1f\n" +
	"\vis_verified\x18\a \x01(\bR\n" +
	"isVerified\"\x9b\x01\n" +
	"\tKeyBundle\x12!\n" +
	"\fidentity_key\x18\x01 \x01(\tR\videntityKey\x12$\n" +
	"\x0esigned_pre_key\x18\x02 \x01(\tR\fsignedPreKey\x12#\n" +
	"\rspk_signature\x18\x03 \x01(\fR\fspkSignature\x12 \n" +
	"\fone_time_key\x18\x04 \x01(\tR\n" +
	"oneTimeKey\"a\n" +
	"\x0fRegisterRequest\x120\n" +
	"\aprofile\x18\x01 \x01(\v2\x16.cortex.v1.UserProfileR\aprofile\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"i\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\faccess_token\x18\x03 \x01(\tR\vaccessToken\"V\n" +
	"\rAuthChallenge\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\tR\x05nonce\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\"r\n" +
	"\tAuthLogin\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\tR\x05nonce\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12\x1f\n" +
	"\vdevice_name\x18\x04 \x01(\tR\n" +
	"deviceName\"v\n" +
	"\rTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\"\xbb\x03\n" +
	"\aImpulse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"sender_did\x18\x03 \x01(\tR\tsenderDid\x12\x19\n" +
	"\bguild_id\x18\x04 \x01(\tR\aguildId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x05 \x01(\tR\tchannelId\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\x12*\n" +
	"\x04chat\x18\n" +
	" \x01(\v2\x14.cortex.v1.ChatEventH\x00R\x04chat\x12.\n" +
	"\x05voice\x18\v \x01(\v2\x16.cortex.v1.VoiceSignalH\x00R\x05voice\x121\n" +
	"\x06system\x18\f \x01(\v2\x17.cortex.v1.SystemSignalH\x00R\x06system\x12?\n" +
	"\tmigration\x18\r \x01(\v2\x1f.cortex.v1.MigrationCertificateH\x00R\tmigration\x120\n" +
	"\x06report\x18\x0e \x01(\v2\x16.cortex.v1.AbuseReportH\x00R\x06reportB\t\n" +
	"\apayload\"\xdc\x02\n" +
	"\tChatEvent\x12<\n" +
	"\brel_type\x18\x01 \x01(\x0e2!.cortex.v1.ChatEvent.RelationTypeR\arelType\x12\x15\n" +
	"\x06ref_id\x18\x02 \x01(\tR\x05refId\x12!\n" +
	"\fis_encrypted\x18\x03 \x01(\bR\visEncrypted\x12\x1f\n" +
	"\n" +
	"plain_text\x18\x04 \x01(\tH\x00R\tplainText\x128\n" +
	"\tencrypted\x18\x05 \x01(\v2\x18.cortex.v1.EncryptedDataH\x00R\tencrypted\x127\n" +
	"\vattachments\x18\x06 \x03(\v2\x15.cortex.v1.AttachmentR\vattachments\"8\n" +
	"\fRelationType\x12\a\n" +
	"\x03NEW\x10\x00\x12\t\n" +
	"\x05REPLY\x10\x01\x12\b\n" +
	"\x04EDIT\x10\x02\x12\n" +
	"\n" +
	"\x06DELETE\x10\x03B\t\n" +
	"\acontent\"\x8e\x01\n" +
	"\rEncryptedData\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x01 \x01(\fR\n" +
	"ciphertext\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm\x12\"\n" +
	"\rsender_key_id\x18\x03 \x01(\tR\vsenderKeyId\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\"w\n" +
	"\n" +
	"Attachment\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\tR\x04hash\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\"\xb4\x01\n" +
	"\vVoiceSignal\x125\n" +
	"\x04type\x18\x01 \x01(\x0e2!.cortex.v1.VoiceSignal.SignalTypeR\x04type\x12\x17\n" +
	"\asfu_url\x18\x02 \x01(\tR\x06sfuUrl\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"?\n" +
	"\n" +
	"SignalType\x12\x10\n" +
	"\fJOIN_REQUEST\x10\x00\x12\x10\n" +
	"\fTOKEN_ISSUED\x10\x01\x12\r\n" +
	"\tUSER_LEFT\x10\x02\"\xfe\x01\n" +
	"\fSystemSignal\x126\n" +
	"\x04type\x18\x01 \x01(\x0e2\".cortex.v1.SystemSignal.SignalTypeR\x04type\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fredirect_url\x18\x03 \x01(\tR\vredirectUrl\x12)\n" +
	"\x10server_signature\x18\x04 \x01(\fR\x0fserverSignature\"N\n" +
	"\n" +
	"SignalType\x12\x0f\n" +
	"\vMAINTENANCE\x10\x00\x12\x16\n" +
	"\x12SHUTDOWN_PERMANENT\x10\x01\x12\x17\n" +
	"\x13MIGRATION_IMMEDIATE\x10\x02\"\x90\x01\n" +
	"\x14MigrationCertificate\x12\x1d\n" +
	"\n" +
	"old_domain\x18\x01 \x01(\tR\toldDomain\x12\x1d\n" +
	"\n" +
	"new_domain\x18\x02 \x01(\tR\tnewDomain\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\"\xae\x01\n" +
	"\vAbuseReport\x12!\n" +
	"\freporter_did\x18\x01 \x01(\tR\vreporterDid\x12*\n" +
	"\x11target_message_id\x18\x02 \x01(\tR\x0ftargetMessageId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x128\n" +
	"\x18ephemeral_decryption_key\x18\x04 \x01(\fR\x16ephemeralDecryptionKey\"J\n" +
	"\x0eGatewayPayload\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\x05R\x02op\x12\f\n" +
	"\x01d\x18\x02 \x01(\fR\x01d\x12\f\n" +
	"\x01t\x18\x03 \x01(\tR\x01t\x12\f\n" +
	"\x01s\x18\x04 \x01(\x03R\x01s*A\n" +
	"\vAccountType\x12\t\n" +
	"\x05HUMAN\x10\x00\x12\r\n" +
	"\tAUTOMATON\x10\x01\x12\r\n" +
	"\tCONSTRUCT\x10\x02\x12\t\n" +
	"\x05PROXY\x10\x03B\x06Z\x04./pbb\x06proto3"

var (
	file_cortex_proto_rawDescOnce sync.Once
	file_cortex_proto_rawDescData []byte
)

func file_cortex_proto_rawDescGZIP() []byte {
	file_cortex_proto_rawDescOnce.Do(func() {
		file_cortex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cortex_proto_rawDesc), len(file_cortex_proto_rawDesc)))
	})
	return file_cortex_proto_rawDescData
}

var file_cortex_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_cortex_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_cortex_proto_goTypes = []any{
	(AccountType)(0),             // 0: cortex.v1.AccountType
	(ChatEvent_RelationType)(0),  // 1: cortex.v1.ChatEvent.RelationType
	(VoiceSignal_SignalType)(0),  // 2: cortex.v1.VoiceSignal.SignalType
	(SystemSignal_SignalType)(0), // 3: cortex.v1.SystemSignal.SignalType
	(*UserProfile)(nil),          // 4: cortex.v1.UserProfile
	(*KeyBundle)(nil),            // 5: cortex.v1.KeyBundle
	(*RegisterRequest)(nil),      // 6: cortex.v1.RegisterRequest
	(*RegisterResponse)(nil),     // 7: cortex.v1.RegisterResponse
	(*AuthChallenge)(nil),        // 8: cortex.v1.AuthChallenge
	(*AuthLogin)(nil),            // 9: cortex.v1.AuthLogin
	(*TokenResponse)(nil),        // 10: cortex.v1.TokenResponse
	(*Impulse)(nil),              // 11: cortex.v1.Impulse
	(*ChatEvent)(nil),            // 12: cortex.v1.ChatEvent
	(*EncryptedData)(nil),        // 13: cortex.v1.EncryptedData
	(*Attachment)(nil),           // 14: cortex.v1.Attachment
	(*VoiceSignal)(nil),          // 15: cortex.v1.VoiceSignal
	(*SystemSignal)(nil),         // 16: cortex.v1.SystemSignal
	(*MigrationCertificate)(nil), // 17: cortex.v1.MigrationCertificate
	(*AbuseReport)(nil),          // 18: cortex.v1.AbuseReport
	(*GatewayPayload)(nil),       // 19: cortex.v1.GatewayPayload
}
var file_cortex_proto_depIdxs = []int32{
	0,  // 0: cortex.v1.UserProfile.type:type_name -> cortex.v1.AccountType
	4,  // 1: cortex.v1.RegisterRequest.profile:type_name -> cortex.v1.UserProfile
	12, // 2: cortex.v1.Impulse.chat:type_name -> cortex.v1.ChatEvent
	15, // 3: cortex.v1.Impulse.voice:type_name -> cortex.v1.VoiceSignal
	16, // 4: cortex.v1.Impulse.system:type_name -> cortex.v1.SystemSignal
	17, // 5: cortex.v1.Impulse.migration:type_name -> cortex.v1.MigrationCertificate
	18, // 6: cortex.v1.Impulse.report:type_name -> cortex.v1.AbuseReport
	1,  // 7: cortex.v1.ChatEvent.rel_type:type_name -> cortex.v1.ChatEvent.RelationType
	13, // 8: cortex.v1.ChatEvent.encrypted:type_name -> cortex.v1.EncryptedData
	14, // 9: cortex.v1.ChatEvent.attachments:type_name -> cortex.v1.Attachment
	2,  // 10: cortex.v1.VoiceSignal.type:type_name -> cortex.v1.VoiceSignal.SignalType
	3,  // 11: cortex.v1.SystemSignal.type:type_name -> cortex.v1.SystemSignal.SignalType
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_cortex_proto_init() }
func file_cortex_proto_init() {
	if File_cortex_proto != nil {
		return
	}
	file_cortex_proto_msgTypes[7].OneofWrappers = []any{
		(*Impulse_Chat)(nil),
		(*Impulse_Voice)(nil),
		(*Impulse_System)(nil),
		(*Impulse_Migration)(nil),
		(*Impulse_Report)(nil),
	}
	file_cortex_proto_msgTypes[8].OneofWrappers = []any{
		(*ChatEvent_PlainText)(nil),
		(*ChatEvent_Encrypted)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cortex_proto_rawDesc), len(file_cortex_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cortex_proto_goTypes,
		DependencyIndexes: file_cortex_proto_depIdxs,
		EnumInfos:         file_cortex_proto_enumTypes,
		MessageInfos:      file_cortex_proto_msgTypes,
	}.Build()
	File_cortex_proto = out.File
	file_cortex_proto_goTypes = nil
	file_cortex_proto_depIdxs = nil
}
